import * as fsPromises from "node:fs/promises";
import * as nodePath from "node:path";
import { fileURLToPath } from "node:url";
import $RefParser from "@apidevtools/json-schema-ref-parser";

const __dirname = nodePath.dirname(fileURLToPath(import.meta.url));

const generationProfileSchemaPath = nodePath.resolve(
  __dirname,
  "../schema/generation-profile.schema.json",
);

const bundledSchema = await $RefParser.bundle(generationProfileSchemaPath);

const stripMetaKeywords = (value: unknown, parentKey = ""): unknown => {
  if (Array.isArray(value)) {
    return value.map((item) => stripMetaKeywords(item, parentKey));
  }

  if (value && typeof value === "object") {
    const entryPairs = Object.entries(value)
      .filter(([key]) => {
        if (parentKey === "properties") {
          return true;
        }

        return key !== "$schema" && key !== "$id";
      })
      .map(([key, child]) => [key, stripMetaKeywords(child, key)]);

    return Object.fromEntries(entryPairs);
  }

  return value;
};

const cleanedSchema = stripMetaKeywords(bundledSchema);
const schemaSource = JSON.stringify(cleanedSchema, null, 2);

const output = `/*
 * This file is auto-generated by scripts/generateGenerationProfileSchema.ts.
 * Do not edit this file manually.
 */

export const generationProfileSchema: Record<string, unknown> = ${schemaSource};
`;

const outputPath = nodePath.resolve(
  __dirname,
  "../generated/schema/generatedGenerationProfileSchema.ts",
);

await fsPromises.writeFile(outputPath, output, "utf8");
console.log(`Generated ${outputPath}`);
