# CI: Runs CI jobs on pushes to specific protected branches and on pull requests.
# Steps:
# * Lint
# * Test
# * Build
name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        # to resolve peer dependency conflict related with eslint-plugin-import-x
        run: npm ci --legacy-peer-deps

      - name: Check generated artifacts are up to date
        run: npm run check:generated -w @gent-js/gent

      - name: Format check
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test --workspaces --if-present

      - name: Build
        run: npm run build --workspaces --if-present
